### PR TITLE
Polymer core & paper

### PR DESCRIPTION
**Pull request by cheleb**
SNAPSHOT versions.

### CODE REVIEW

**Comment by cheleb** [comment]
Did you give a try ?

**Comment by jamesward** [comment]
I think that using Bower WebJars for these is going to be more maintainable.  Can you try to create what you need: http://www.webjars.org/bower

**Comment by waldemar-schneider** [comment]
On the recent Google IO polymer 1.0 was released. @cheleb is it possible that you include the 1.0 release?

**Comment by cheleb** [comment]
I'll give a try asap.


On Sat, May 30, 2015 at 11:22 AM, Waldemar Schneider <
notifications@github.com> wrote:

> On the recent Google IO polymer 1.0 was released. @cheleb
> <https://github.com/cheleb> is it possible that you include the 1.0
> release?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webjars/polymer/pull/8#issuecomment-107016282>.
>



-- 
"Computers are useless. They can only give you answers."
- Pablo Picasso -

**Comment by cheleb** [comment]
Hi all,
  After a quick look:

   - I don't really know where to put such webjars, @james prefer bower
   "webjar". I could deploy them with different GAV (org.webjar.polymers for
   testing).
   - Do you really think webjar are usable without treeshaking/minification
   (vulcanization) ?



On Sun, May 31, 2015 at 12:10 AM, Olivier NOUGUIER <
olivier.nouguier@gmail.com> wrote:

> I'll give a try asap.
>
>
> On Sat, May 30, 2015 at 11:22 AM, Waldemar Schneider <
> notifications@github.com> wrote:
>
>> On the recent Google IO polymer 1.0 was released. @cheleb
>> <https://github.com/cheleb> is it possible that you include the 1.0
>> release?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/webjars/polymer/pull/8#issuecomment-107016282>.
>>
>
>
>
> --
> "Computers are useless. They can only give you answers."
> - Pablo Picasso -
>



-- 
"Computers are useless. They can only give you answers."
- Pablo Picasso -

**Comment by jamesward** [comment]
Maintaining these libraries manually via the Classic WebJars (created from Maven builds) is possible but a lot of work.  That is why it would be better to do these as Bower WebJars.  But the problem with doing these as Bower WebJars is that not all of the dependencies have been published in Bower.  Ideally all of the dependencies would be in Bower.  The only workaround for this is handling the git-based dependencies but that work hasn't been done yet: https://github.com/webjars/webjars/issues/1044

Minification is usually being done either by the upstream project (e.g. adding a `dist` dir with the minified assets).  Alternatively the user's asset pipeline / build system should do this.

**Pull request closed without merging**
